### ISSUE TITLE
[Feature Request] Reimplement PS3 vehicle reflections for Carbon

### ISSUE THREAD

**Issue by sinisterseed** [AeroWidescreen/NFSHDReflections#1]
Hello there.

I have made a similar request in the past, but since the HD Reflection collection of mods has been consolidated into a single package, their download pages as well as their Git repositories have understandably been deleted.

As a result, I have returned with the same old request. Old versions of the HD Reflections mod for Carbon offered the ability to choose between both X360 and PS3 versions, with the PS3 version being removed in an update. I would like to request its revival if at all possible, seeing how there have been many updates since, which aim to bring the experience as close as possible to the X360 version. 

But since the mod offers a toggle for the purple-tinted filter that was likely used on the PS3 version too, I was thinking the two features could nicely complement each other so players can easily alternate between the two if desired. That being said, if this goes against the established vision for the mod and isn't worth the effort, I can simply close my request.

**Comment by AeroWidescreen** [comment]
Yeah, sure, I'll look into it soon.

**Comment by AeroWidescreen** [comment]
Updated. Here's some information that might help you get the results you want:

Install:
[Widescreen Fix](https://nfsmods.xyz/mod/3327) (update if you haven't in the past 60 days)
[PS3 Visual Treatment](https://nfsmods.xyz/mod/3473)
[HUD Resizer](https://nfsmods.xyz/mod/1206)
[HD Vinyls](https://nfsmods.xyz/mod/2349)

HD Reflection settings to change:

> [RESOLUTION]
>  VehicleScale = 0.25
> 
> [GENERAL]
> ReflectionContrast = 2
> ForceEnvironmentMap = 5
> AspectRatioFix = 0
> 
> [EXTRA]
> ReplaceVisualTreatmentIG = 0 
> ReplaceVisualTreatmentFE = 0
> RealisticChrome = 1

![FrontEnd](https://i.imgur.com/tM352k1.png)
![InGame](https://i.imgur.com/Z81Ht7G.png)

**Comment by sinisterseed** [comment]
Thanks Aero, appreciate the effort you put into this 👍.

I'm surprised there is a PS3 Visual Treatment filter mod now, though. The unused purple tinted filter was actually not the one that was also used on the PS3?

**Comment by AeroWidescreen** [comment]
I've updated HD Reflections again. You can use `RestoreDetails = 2` to add particle effects to the rearview mirror, like the PS3 version. Anyway, I'm going to close this now.

> Now if only the missing light trails could be re-enabled. I was reading through the comments on your PS3 filter demo, and Xan claims that the code is all still there even on PC, it's just not working for some reason.

I've asked Xan and it seems like he thinks PS3 trails can be done at least. He's busy right now but he'll look into it later he claims. I guess we'll see how it goes.

**Comment by sinisterseed** [comment]
Fair enough, the ticket has fulfilled its purpose at this point. Glad to see what came out of it 😁.

I'll be looking forward to the PS3 trails as well, see how that one goes, if it does get done at all.
