### ISSUE TITLE
Set Resolution Manually instead of basing it on Desktop Resolution.

### ISSUE THREAD

**Issue by XzRaiderzX** [AeroWidescreen/NFSHDReflections#11]
Back in the day it was possible to set the resolution for the X and Y axis separately. I tinkered with that and realized it's possible optimize reflections by setting the vertical resolution higher and lowering horizontal, since reflections are almost always at a steep enough angle for the horizontal resolution to be irrelevant [(A technique Insomniac used for raytraced water reflections in the last spiderman title.)](https://youtu.be/fuu_wseJnIE?si=LDaRxFVoxrrtE9kX&t=647). It also kinda resulted in more realistic reflections that had improved clarity while retaining roughness/ not being uniformly sharp. 
Nowadays you can't get that effect because it's strictly scaling by the desktop res and I find this disappointing, especially since that's backwards-ly rendering more on the horizontal plane than vertical. 

For example here's the quality difference in ProStreet; Reflections at 1440p and 0.375x scaling:
![Need for Speed  ProStreet Screenshot 2024 02 10 - 20 44 49 04](https://github.com/AeroWidescreen/NFSHDReflections/assets/156614762/abf7ac7b-0c24-4ddf-a6e1-c2608f143ecb)

Compared to the original resolution (512x512 iirc), but at 5x scaling
![Need for Speed  ProStreet Screenshot 2024 02 10 - 20 42 40 93](https://github.com/AeroWidescreen/NFSHDReflections/assets/156614762/c2ca54c8-a6dd-4353-8b4e-7ad40fbad1ef)
The latter has much more clarity, while also using less resources (1,382,400 pixels vs 1,310,720).
So would it be possible to reimplement setting X/Y axis separately?

**Comment by AeroWidescreen** [comment]
I apologize for the late response. Your suggestion seems fair and makes a lot of sense to me, so I'll look into it later. Just don't expect anything soon because NFS modding isn't a priority for me at the moment.

**Comment by XzRaiderzX** [comment]
No worries, the mod in it's current state is plenty as is so take the time you need. I'm glad you considered this change ☺️ ❤️

**Comment by XzRaiderzX** [comment]
No worries, the mod in it's current state is plenty as is so take the time you need. I'm glad you considered this change ☺️ ❤️
