### ISSUE TITLE
Update latest release to include pull request #2

### ISSUE THREAD

**Issue by ruanformigoni** [AeroWidescreen/NFSHDReflections#3]
Hi!

Could you please update the release in `https://nfsmods.xyz/mod/3363` to include the changes in pull request #2? Thank you!

**Comment by AeroWidescreen** [comment]
Here: 
[NFSPSHDReflections.zip](https://github.com/AeroWidescreen/NFSHDReflections/files/9269523/NFSPSHDReflections.zip)

I don't plan on officially updating anything right now because I have a few other things I need to do first.
