### ISSUE TITLE
Objects, Particles, Tire marks  and other stuff not rendering in rearview

### ISSUE THREAD

**Issue by YellowDud3** [AeroWidescreen/NFSHDReflections#4]
so uh, in the MW 2005 version of the mod, the objects disappear in the rear view but they still show the shadows, tire marks, and particles wont appear either. Basically, a lot of things don't get rendered in the rearview, any plans for a fix?
![Need for Speed™ Most Wanted 10_24_2022 12_58_45 PM](https://user-images.githubusercontent.com/116546327/197471149-ee0ea889-9f0c-4f6b-965a-460a7ad4acd7.png)

**Comment by AeroWidescreen** [comment]
`RestoreDetails = 2` will render particle effects in the mirror. 

> the objects disappear in the rear view but they still show the shadows

Download HD Reflections again, as I've released an update that should make those objects visible. I have no plans to add tire marks, or anything else, at this time.

**Comment by YellowDud3** [comment]
> `RestoreDetails = 2` will render particle effects in the mirror.
> 
> > the objects disappear in the rear view but they still show the shadows
> 
> Download HD Reflections again, as I've released an update that should make those objects visible. I have no plans to add tire marks, or anything else, at this time.

it works now, hopefully you'd add the tire marks someday, but for now: thanks
