### ISSUE TITLE
Headlights in ground reflections

### ISSUE THREAD

**Issue by TorutheRedFox** [AeroWidescreen/NFSHDReflections#9]
_Another_ leftover that got removed in the Xbox 360 release, probably because it illuminates the sea.

I noticed it's present in the original Xbox release too, haven't checked PS2 or GameCube though.

**Comment by AeroWidescreen** [comment]
https://github.com/AeroWidescreen/NFSHDReflections/commit/efc3ca2b10deb0cb6e12c29af7065c61d20a6fa1
